image: node:8

stages:
  - test
  - build
  - deploy

before_script:
  - yarn install

cache:
  paths:
    - node_modules/

test:
  tags:
    - docker
  stage: test
  script:
    - yarn test

build:
  tags:
    - docker
  stage: build
  script:
    - yarn build
  artifacts:
    paths:
      - build/

deploy:
  tags:
    - docker
  stage: deploy
  environment:
    name: production
    url: http://connectedworldsteam10.surge.sh/
  dependencies:
    - build
  script:
    - npm install surge
    - surge --project ./build --domain http://connectedworldsteam10.surge.sh/
  only:
    - master
