version: 2
jobs:
  lint:
    docker:
      - image: python:3.7
    steps:
      - checkout
      - run: pip install flake8
      - run: flake8
  parse:
    docker:
      - image: python:3.7
    steps:
      - checkout
      - run: cd parser && python csv_parser.py
      - persist_to_workspace:
          root: ~/project
          paths:
            - public/*

  test:
    docker:
      - image: node:8
    steps:
      - checkout
      - run: yarn install
      - run: yarn test

  build:
    docker:
      - image: node:8
    steps:
      - checkout
      - run: yarn install
      - run: mv parser/output/output.json src/assets
      - run: mv parser/output/years.json src/assets
      - run: yarn build
      - store_artifacts:
          path: ~/project/build
      - persist_to_workspace:
          root: ~/project
          paths:
            - build/*
  deploy:
    docker:
      - image: node:8
    steps:
      - attach_workspace:
          at: ~/project
      - run: "npm install surge --global"
      - run: "surge --project ./build --domain $URL"
workflows:
  version: 2
  test-build-deploy:
    jobs:
      - lint
      - parse
      - test
      - build:
          requires:
            - parse
      - deploy:
          requires:
            - test
            - build
          filters:
            branches:
              only: master
